### ISSUE TITLE
Why split from pypi-mobans repo?

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans-pkg#3]
Why is the release/packaging done in a separate repo from https://github.com/moremoban/pypi-mobans ?

**Comment by chfw** [comment]
It is the pkg's directory structure. If overlapped, pypi-mobans will hidden and will cause a lot of directory update downstream.

And with separate pkg repo, it is less confusing, whatever you see here is not part of pypi-mobans. If overlapped, the noise level increases.

**Comment by jayvdb** [comment]
Ya ok.
Thanks.
